import type { CandidateProfile, ViewerProfile } from "@/lib/types";

export const defaultViewerSeed: ViewerProfile = {
  fid: null,
  username: "you",
  displayName: "You",
  bio: "Building Overlap for people who want better collaborator discovery than follower count and raw clout.",
  avatar: {
    initials: "OV",
    start: "#8A5CFF",
    end: "#27D7FF",
  },
  discovery: {
    roles: ["builder", "creator"],
    ecosystems: ["base"],
    interests: ["ai", "mini_apps", "agents"],
    seeking: ["feedback", "brainstorm"],
    offering: ["build", "brainstorm"],
    about: "I care about social discovery products that feel useful in the first five minutes.",
    building: "A Farcaster mini app that ranks collaborator overlap using profile + activity + graph context.",
  },
  activity: {
    sampleCasts: [
      "Mini apps should explain why a match matters before asking for action.",
      "Still convinced social products work best when intent and timing carry more weight than clout.",
    ],
    extractedInterests: ["ai", "mini_apps", "agents", "content"],
    extractedEcosystems: ["base", "eth_mainnet"],
    channels: ["miniapps", "builders", "base"],
    castsLast7d: 8,
    repliesLast7d: 9,
    activeDays7d: 5,
    activeDays30d: 18,
    lastActiveAt: "2026-03-19T20:25:00.000Z",
    followingFids: [11, 18, 21, 28, 35, 41, 59],
    followerCount: 0,
  },
};

export const seedCandidates: CandidateProfile[] = [
  {
    id: "lina-park",
    fid: null,
    username: "linapark",
    displayName: "Lina Park",
    bio: "Builder-creator shipping AI-native social surfaces on Base. Wants motion-heavy collaborators who move fast.",
    avatar: {
      initials: "LP",
      start: "#7C3AED",
      end: "#F472B6",
    },
    discovery: {
      roles: ["builder", "creator"],
      ecosystems: ["base", "hyperliquid"],
      interests: ["ai", "agents", "mini_apps", "content"],
      seeking: ["designer", "distribution"],
      offering: ["build", "brainstorm", "role_opening"],
      about: "I like shipping opinionated social products with strong visual identity.",
      building: "An AI-first discovery loop for builders on Base.",
    },
    activity: {
      sampleCasts: [
        "Agent UX still feels half-finished. Working on a more human mini app loop on Base.",
        "Need a design partner who likes shipping motion-heavy social tools this quarter.",
      ],
      extractedInterests: ["ai", "agents", "mini_apps", "content"],
      extractedEcosystems: ["base", "hyperliquid"],
      channels: ["miniapps", "base", "agents"],
      castsLast7d: 12,
      repliesLast7d: 7,
      activeDays7d: 6,
      activeDays30d: 22,
      lastActiveAt: "2026-03-19T18:10:00.000Z",
      followingFids: [11, 18, 32, 41, 88],
      followerCount: 1284,
    },
    neynarScore: 0.86,
  },
  {
    id: "jo-rivera",
    fid: null,
    username: "jorivera",
    displayName: "Jo Rivera",
    bio: "Builder-trader shipping gamey DeFi products. Hiring builders who care about onboarding and distribution.",
    avatar: {
      initials: "JR",
      start: "#2563EB",
      end: "#06B6D4",
    },
    discovery: {
      roles: ["builder", "trader"],
      ecosystems: ["base", "eth_mainnet"],
      interests: ["defi", "mini_apps", "gaming"],
      seeking: ["dev", "distribution"],
      offering: ["role_opening", "feedback"],
      about: "I want product people who can move between growth and UX without hand-holding.",
      building: "A DeFi product that feels playful enough to share.",
    },
    activity: {
      sampleCasts: [
        "If your DeFi product is fun enough to share, distribution gets materially easier.",
        "Looking for one more builder who can move between app logic and UX polish.",
      ],
      extractedInterests: ["defi", "mini_apps", "gaming", "content"],
      extractedEcosystems: ["base", "eth_mainnet"],
      channels: ["base", "builders", "defi"],
      castsLast7d: 10,
      repliesLast7d: 5,
      activeDays7d: 5,
      activeDays30d: 20,
      lastActiveAt: "2026-03-18T23:42:00.000Z",
      followingFids: [18, 28, 41, 63, 77],
      followerCount: 2031,
    },
    neynarScore: 0.8,
  },
  {
    id: "aya-sato",
    fid: null,
    username: "ayasato",
    displayName: "Aya Sato",
    bio: "Artist-creator building collectible story worlds across Base and Solana. Open to playful experiments, not stale brand asks.",
    avatar: {
      initials: "AS",
      start: "#EC4899",
      end: "#F59E0B",
    },
    discovery: {
      roles: ["artist", "creator"],
      ecosystems: ["base", "solana"],
      interests: ["nfts", "content", "memes"],
      seeking: ["brainstorm", "distribution"],
      offering: ["design", "brainstorm"],
      about: "The best collectible drops still feel like tiny cultural worlds.",
      building: "A story-led collectible universe with social mechanics.",
    },
    activity: {
      sampleCasts: [
        "The best NFT drops still feel like tiny cultural worlds, not just inventory.",
        "Would love to jam with builders who get playful social mechanics.",
      ],
      extractedInterests: ["nfts", "content", "memes", "gaming"],
      extractedEcosystems: ["base", "solana"],
      channels: ["nfts", "creators", "base"],
      castsLast7d: 7,
      repliesLast7d: 8,
      activeDays7d: 4,
      activeDays30d: 15,
      lastActiveAt: "2026-03-17T16:05:00.000Z",
      followingFids: [11, 19, 41, 52],
      followerCount: 948,
    },
    neynarScore: 0.73,
  },
  {
    id: "miko-vale",
    fid: null,
    username: "mikovale",
    displayName: "Miko Vale",
    bio: "Trader-builder focused on Hyperliquid and agent workflows. Likes structured thinking and crisp asks.",
    avatar: {
      initials: "MV",
      start: "#0EA5E9",
      end: "#6366F1",
    },
    discovery: {
      roles: ["trader", "builder"],
      ecosystems: ["hyperliquid", "solana"],
      interests: ["ai", "trading", "agents"],
      seeking: ["feedback", "brainstorm"],
      offering: ["feedback"],
      about: "I care about guardrails, market structure, and making automation legible.",
      building: "Execution research around Hyperliquid plus agent workflows.",
    },
    activity: {
      sampleCasts: [
        "Agentic trading UX needs much better guardrails before it reaches normal users.",
        "Exploring how Hyperliquid social data can sharpen execution decisions.",
      ],
      extractedInterests: ["ai", "trading", "agents"],
      extractedEcosystems: ["hyperliquid", "solana"],
      channels: ["trading", "agents", "research"],
      castsLast7d: 11,
      repliesLast7d: 4,
      activeDays7d: 6,
      activeDays30d: 24,
      lastActiveAt: "2026-03-19T12:12:00.000Z",
      followingFids: [7, 18, 21, 59, 77],
      followerCount: 1111,
    },
    neynarScore: 0.7,
  },
  {
    id: "rafa-kent",
    fid: null,
    username: "rafakent",
    displayName: "Rafa Kent",
    bio: "Creator translating technical products into narratives that travel. Strong distribution, lighter on product depth.",
    avatar: {
      initials: "RK",
      start: "#14B8A6",
      end: "#84CC16",
    },
    discovery: {
      roles: ["creator"],
      ecosystems: ["base", "eth_mainnet"],
      interests: ["content", "memes", "socialfi"],
      seeking: ["brainstorm"],
      offering: ["distribution", "brainstorm"],
      about: "If people cannot explain your product in one sentence, distribution stalls.",
      building: "Narrative systems for technical products that need better top-of-funnel reach.",
    },
    activity: {
      sampleCasts: [
        "If people cannot explain your product in one sentence, distribution stalls.",
        "Still bullish on creators who learn enough product to be dangerous.",
      ],
      extractedInterests: ["content", "memes", "socialfi"],
      extractedEcosystems: ["base", "eth_mainnet"],
      channels: ["creators", "socialfi", "base"],
      castsLast7d: 9,
      repliesLast7d: 11,
      activeDays7d: 7,
      activeDays30d: 25,
      lastActiveAt: "2026-03-19T19:00:00.000Z",
      followingFids: [28, 35, 41, 90],
      followerCount: 1877,
    },
    neynarScore: 0.76,
  },
  {
    id: "deon-reed",
    fid: null,
    username: "deonreed",
    displayName: "Deon Reed",
    bio: "Builder-creator obsessed with lightweight social tools. Looking for co-builders who want to move from prototype to product fast.",
    avatar: {
      initials: "DR",
      start: "#8B5CF6",
      end: "#22C55E",
    },
    discovery: {
      roles: ["builder", "creator"],
      ecosystems: ["base", "eth_mainnet"],
      interests: ["ai", "mini_apps", "content", "agents"],
      seeking: ["cofounder", "feedback"],
      offering: ["build", "brainstorm"],
      about: "I like products that explain the graph before asking for action.",
      building: "A collaborator graph for mini app builders.",
    },
    activity: {
      sampleCasts: [
        "More mini apps should explain the social graph before asking for action.",
        "Looking for a collaborator who likes product strategy as much as shipping the interface.",
      ],
      extractedInterests: ["ai", "mini_apps", "content", "agents"],
      extractedEcosystems: ["base", "eth_mainnet"],
      channels: ["miniapps", "builders", "content"],
      castsLast7d: 13,
      repliesLast7d: 10,
      activeDays7d: 7,
      activeDays30d: 26,
      lastActiveAt: "2026-03-19T20:05:00.000Z",
      followingFids: [11, 18, 21, 28, 41, 59],
      followerCount: 1645,
    },
    neynarScore: 0.84,
  },
];
